version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  hello:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo "Hello"
  bye:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo "Bye"
workflows:
  echo:
    jobs:
      - hello
      - bye
